### ISSUE TITLE
Plugin only reads certain Battle log lines

### ISSUE THREAD

**Issue by PaintAPicture** [Ms-Tress/AetherSense#3]
Hello! I wasn't sure whether there was a better place to post this.

I tried out AetherSense, and where it works, it works perfectly! However, I noticed that only certain of the default triggers were working, and was having inconsistent results with editing/making new ones.

I eventually figured out that the plugin seems to only be reading lines in the battle log which are preceded by an arrow: these appear to be 'results' lines that occur as a result of an action. An enemy taking damage works (when in the form '-> [Enemy] takes X damage', not 'You hit the [enemy] for X damage') , as does gaining an effect from casting a spell, but 'You begin to cast' and 'You cast', for example, do not. Example provided below.

Hope this is useful! The ability to set patterns is great, and I would love to see the plugin fully functional.

![aethersense](https://user-images.githubusercontent.com/80420719/110681122-5d654d00-81d1-11eb-994e-178018edd35e.png)

**Comment by ghost** [comment]
Aha, tracked this one down. Aether Sense was discarding any messages that started with "You" so "You hit the striking dummy" was always ignored.

Fix incoming~

**Comment by PaintAPicture** [comment]
That’s wonderful! Thank you so much! ^_^
