### ISSUE TITLE
I play with my girlfriend, and i'd love to have the plugin trigger when i heal her specifically

### ISSUE THREAD

**Issue by EmmyKiwi** [Ms-Tress/AetherSense#5]
Would it be possible to add an option alongside "Only self" that would work similarly but you'd type their names there and it'd trigger the plugin, much like "Only self"

**Comment by ghost** [comment]
good suggestion! I'll investigate this when I get the chance.

Until then, you could potentially set a trigger like "EmmyKiwi casts Cure" to trigger on all cure casts done by another character, but that will be regardless of target.
