### ISSUE TITLE
Aether Sense config keeps opening itself.

### ISSUE THREAD

**Issue by lovelydumpling** [Ms-Tress/AetherSense#6]
After the update to XIVLauncher today, the AetherSense config opens on its own when starting up the game. Every time I close it, it opens back up two seconds later. I have to disable the plugin entirely to keep it off my screen.

**Comment by ghost** [comment]
The configuration editor should open automatically if a connection to Intiface Desktop (or other buttplug.io server) cant be connected. 
So you will need to disable the plugin in the plugin manager, or disable the connection in the AetherSense configuration window to stop it.

**Comment by lovelydumpling** [comment]
_Ooooooooh. This makes sense._ I feel like I've missed something obvious.

This works fine, thank you.
